### ISSUE TITLE
剪枝前后速度问题

### ISSUE THREAD

**Issue by HandsLing** [DDGRCF/yolov5_Chinese#1]
## ❔Question
大佬你好，我发现剪枝前后速度竟然没有一边变化，同一张图片剪枝前后速度竟然都是20ms，而且我加载了之前直接用yolov5训练的模型发现只要10ms，大佬你之前测试速度是咋样的呢？

**Comment by DDGRCF** [comment]
> ## Question
> 大佬你好，我发现剪枝前后速度竟然没有一边变化，同一张图片剪枝前后速度竟然都是20ms，而且我加载了之前直接用yolov5训练的模型发现只要10ms，大佬你之前测试速度是咋样的呢？
> 
> ## Additional context

应该是我采用原文对于short_cut的处理所导致的并行计算的原因，你可以看一下common_prunig中的bottleneck中的forward的处理，我猜就是那里导致的。因为前段时间开学比较忙，这个做到一半就停下了。我近期准备在我的另一个yolov5_pruning的项目中重新实验一下。最后十分感谢你对我的这个github项目感兴趣。

**Comment by DDGRCF** [comment]
应该是其中的并行操作导致的 从 Windows 版邮件发送 发件人: HandsLing发送时间: 2021年8月31日 9:30收件人: DDGRCF/yolov5_Chinese抄送: Subscribed主题: [DDGRCF/yolov5_Chinese] 剪枝前后速度问题 (#1) ❔Question大佬你好，我发现剪枝前后速度竟然没有一边变化，同一张图片剪枝前后速度竟然都是20ms，而且我加载了之前直接用yolov5训练的模型发现只要10ms，大佬你之前测试速度是咋样的呢？Additional context—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
